mediequip_postgres:
  outputs:
    dev:
      dbname: mediequip_dw
      host: localhost
      pass: 
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: mediequip_dbt
    prod:  
      type: postgres
      host: localhost
      user: mediequip_dbt
      password: 
      port: 5433
      dbname: mediequip_dw
      schema: marts
      threads: 4
  target: dev
