mediequip_postgres:
  outputs:
    dev:
      dbname: mediequip_dw
      host: localhost
      pass: 
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: mediequip_dbt
  target: dev
